// Auth constants
export const USER_GAMESHEETS_REQUEST = "USER_GAMESHEETS_REQUEST";
export const USER_GAMESHEETS_RECEIVED = "USER_GAMESHEETS_RECEIVED";
export const USER_GAMESHEETS_ERROR = "USER_GAMESHEETS_ERROR";
export const USER_GAMESHEETS_UNLOAD = "USER_GAMESHEETS_UNLOAD";

export const USER_CARDS_REQUEST = "USER_CARDS_REQUEST";
export const USER_CARDS_RECEIVED = "USER_CARDS_RECEIVED";
export const USER_CARDS_ERROR = "USER_CARDS_ERROR";
export const USER_CARDS_UNLOAD = "USER_CARDS_UNLOAD";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_SET_ID = "USER_SET_ID";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_REGISTER_COMPLETE = "USER_REGISTER_COMPLETE";
export const BOOKMARKS_UPDATED = "BOOKMARKS_UPDATED";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";

// Card Actions
export const RANDOM_CARD_RECEIVED = "RANDOM_CARD_RECEIVED";
export const RANDOM_CARD_ERROR = "RANDOM_CARD_ERROR";
export const RANDOM_CARD_UNLOAD = "RANDOM_CARD_UNLOAD";

export const CARDS_REQUEST = "CARDS_REQUEST";
export const CARDS_RECEIVED = "CARDS_RECEIVED";
export const CARDS_ERROR = "CARDS_ERROR";
export const CARDS_UNLOAD = "CARDS_UNLOAD";

export const CARDS_SEARCH_REQUEST = "CARDS_SEARCH_REQUEST";
export const CARDS_SEARCH_RECEIVED = "CARDS_SEARCH_RECEIVED";
export const CARDS_SEARCH_ERROR = "CARDS_SEARCH_ERROR";
export const CARDS_SEARCH_UNLOAD = "CARDS_SEARCH_UNLOAD";

export const LIKES_UPDATED = "LIKES_UPDATED";
export const CARDS_VALIDATION_UPDATE = "CARDS_VALIDATION_UPDATE";
export const CARDS_DELETE_UPDATE = "CARDS_DELETE_UPDATE";

export const CARD_EDIT = "CARD_EDIT";
export const SENDING_CARD = "SENDING_CARD";
export const SENDING_CARD_END = "SENDING_CARD_END";

// Difficulty Actions
export const DIFFICULTIES_ERROR = "DIFFICULTIES_ERROR";
export const DIFFICULTIES_RECEIVED = "DIFFICULTIES_RECEIVED";
export const DIFFICULTIES_UNLOAD = "DIFFICULTIES_UNLOAD";

// Flash Message Actions
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";

// Gamesheet Actions
export const GAMESHEET_LIST_REQUEST = "GAMESHEET_LIST_REQUEST";
export const GAMESHEET_LIST_RECEIVED = "GAMESHEET_LIST_RECEIVED";
export const GAMESHEET_LIST_ERROR = "GAMESHEET_LIST_ERROR";
export const GAMESHEET_LIST_UNLOAD = "GAMESHEET_LIST_UNLOAD";

export const GAMESHEET_SEARCH_REQUEST = "GAMESHEET_SEARCH_REQUEST";
export const GAMESHEET_SEARCH_RECEIVED = "GAMESHEET_SEARCH_RECEIVED";
export const GAMESHEET_SEARCH_ERROR = "GAMESHEET_SEARCH_ERROR";
export const SEARCH_UNLOAD = "SEARCH_UNLOAD";

export const GAMESHEET_REQUEST = "GAMESHEET_REQUEST";
export const GAMESHEET_RECEIVED = "GAMESHEET_RECEIVED";
export const GAMESHEET_ERROR = "GAMESHEET_ERROR";
export const GAMESHEET_UNLOAD = "GAMESHEET_UNLOAD";

export const UNPUBLISHED_GAMESHEETS_RECEIVED =
  "UNPUBLISHED_GAMESHEETS_RECEIVED";
export const UNPUBLISHED_GAMESHEETS_ERROR = "UNPUBLISHED_GAMESHEETS_ERROR";
export const GAMESHEET_VALIDATION_UPDATE = "GAMESHEET_VALIDATION_UPDATE";
export const GAMESHEET_DELETE_UPDATE = "GAMESHEET_DELETE_UPDATE";
export const GAMESHEET_EDIT = "GAMESHEET_EDIT";
export const UNPUBLISHED_GAMESHEETS_REQUEST = "UNPUBLISHED_GAMESHEETS_REQUEST";
export const UNPUBLISHED_GAMESHEETS_UNLOAD = "UNPUBLISHED_GAMESHEETS_UNLOAD";

export const SENDING_GAMESHEET_END = "SENDING_GAMESHEET_END";
export const SENDING_GAMESHEET = "SENDING_GAMESHEET";

// Image Actions
export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";
export const IMAGE_UNLOAD = "IMAGE_UNLOAD";
export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const AVATAR_UPLOADED = "AVATAR_UPLOADED";
export const AVATAR_REQUEST = "AVATAR_REQUEST";

// Modal Actions
export const SET_MODAL_STATE = "SET_MODAL_STATE";
export const MODAL_UNLOAD = "MODAL_UNLOAD";
export const OPEN_CARD_FORM = "OPEN_CARD_FORM";
export const OPEN_GAMESHEET_FORM = "OPEN_GAMESHEET_FORM";
